# originally generated by datamodel-codegen:
#   filename:  config-schema.json
#   timestamp: 2024-12-04T08:15:20+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, Field

from olot.utils.types import MapStringObject, MapStringString


class Type(Enum):
    layers = 'layers'


class Rootfs(BaseModel):
    diff_ids: list[str]
    type: Type


class HistoryItem(BaseModel):
    created: str | None = None # A combined date and time at which the layer was created, formatted as defined by RFC 3339, section 5.6.
    author: str | None = None
    created_by: str | None = None
    comment: str | None = None
    empty_layer: bool | None = None


# class MapStringObject(BaseModel):
#     __root__: Dict[constr(regex=r'.{1,}'), Dict[str, Any]]


# class Int8(BaseModel):
#     __root__: conint(ge=-128, le=127)


# class Int16(BaseModel):
#     __root__: conint(ge=-32768, le=32767)


# class Int32(BaseModel):
#     __root__: conint(ge=-2147483648, le=2147483647)


# class Int64(BaseModel):
#     __root__: conint(ge=-9223372036854776000, le=9223372036854776000)


# class Uint8(BaseModel):
#     __root__: conint(ge=0, le=255)


# class Uint16(BaseModel):
#     __root__: conint(ge=0, le=65535)


# class Uint32(BaseModel):
#     __root__: conint(ge=0, le=4294967295)


# class Uint64(BaseModel):
#     __root__: conint(ge=0, le=18446744073709552000)


# class Uint16Pointer(BaseModel):
#     __root__: Optional[Uint16]


# class Uint64Pointer(BaseModel):
#     __root__: Optional[Uint64]


# class Base64(BaseModel):
#     __root__: str


# class StringPointer(BaseModel):
#     __root__: Optional[str]


# class MapStringString(BaseModel):
#     __root__: Dict[constr(regex=r'.{1,}'), str]


class Config(BaseModel):
    User: str | None = None
    ExposedPorts: MapStringObject | None = None
    Env: list[str] | None = None
    Entrypoint: list[str] | None = None
    Cmd: list[str] | None = None
    Volumes: MapStringObject | None = None
    WorkingDir: str | None = None
    Labels: MapStringString | None = None
    StopSignal: str | None = None
    ArgsEscaped: bool | None = None


class OCIManifestConfig(BaseModel):
    created: datetime | None = None
    author: str | None = None
    architecture: str
    variant: str | None = None
    os: str
    os_version: str | None = Field(None, alias='os.version')
    os_features: list[str] | None = Field(None, alias='os.features')
    config: Config | None = None
    rootfs: Rootfs
    history: list[HistoryItem] | None = None
