# originally generated by datamodel-codegen using https://github.com/modelpack/model-spec/blob/8f6beb752394e5c6653cfcb3d2cd21950296dfac/schema/config-schema.json
#   filename:  config-schema.json
#   timestamp: 2025-07-04T09:20:40+00:00

from __future__ import annotations

from datetime import datetime
from enum import Enum

from pydantic import BaseModel, ConfigDict, Field


class ModelDescriptor(BaseModel):
    model_config = ConfigDict(extra='forbid')

    createdAt: datetime | None = None
    authors: list[str] | None = None
    family: str | None = None
    name: str | None = Field(None, min_length=1)
    docURL: str | None = None
    sourceURL: str | None = None
    version: str | None = None
    revision: str | None = None
    vendor: str | None = None
    licenses: list[str] | None = None
    title: str | None = None
    description: str | None = None


class Type(Enum):
    layers = 'layers'


class ModelFS(BaseModel):
    model_config = ConfigDict(extra='forbid')

    type: Type
    diffIds: list[str] = Field(..., min_length=1)


class Modality(Enum):
    text = 'text'
    image = 'image'
    audio = 'audio'
    video = 'video'
    embedding = 'embedding'
    other = 'other'


class ModelCapabilities(BaseModel):
    inputTypes: list[Modality] | None = None
    outputTypes: list[Modality] | None = None
    knowledgeCutoff: datetime | None = None
    reasoning: bool | None = None
    toolUsage: bool | None = None


class ModelConfig(BaseModel):
    model_config = ConfigDict(extra='forbid')

    architecture: str | None = None
    format: str | None = None
    paramSize: str | None = None
    precision: str | None = None
    quantization: str | None = None
    capabilities: ModelCapabilities | None = None


class Model(BaseModel):
    model_config = ConfigDict(extra='forbid')

    descriptor: ModelDescriptor
    modelfs: ModelFS
    config: ModelConfig
